config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#failure'
  get 'log', to: 'home#log', as: :log
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'search', to: 'search#index', as: :search
  get 'repos', to: 'repos#index', as: :repos

  root to: 'home#index'
end

app/models/admin_user.rb
# AdminUser
# Administrative User for ActiveAdmin
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/git_hub.rb
# GitHub
# Party down with Github
class GitHub
  include HTTParty
  base_uri 'https://api.github.com'

  # '/?q=tetris+language:assembly&sort=stars&order=desc'
  # def initialize(service, page)
  #   @options = { query: {site: service, page: page} }
  # end

  # 'https://api.github.com/search/repositories?q=tetris+language:assembly&sort=stars&order=desc'
  def repositories(q, options = {})
    options.merge!(q: q)
    # binding.pry
    self.class.get('/search/repositories', options)
  end
end

app/models/search_result.rb
# class SearchResult
#   include Virtus
#
#   extend ActiveModel::Naming
#   include ActiveModel::Conversion
#
#   attr_accessor :name, :zip_code
#
#   def persisted?
#     false
#   end
# end
class SearchResult
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  # include ActiveModel::Validations

  attr_reader :id, :language, :name, :stargazers_count

  def initialize(attributes = {})
    @id = attributes[:id]
    @language = attributes[:language]
    @name = attributes[:name]
    @stargazers_count = attributes[:stargazers_count]
  end

  # def persisted?
  #   false
  # end
end

app/models/user.rb
# User
class User < ActiveRecord::Base
  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: { scope: :provider }
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :authenticate_user!

  private

  def authenticate_user!
    if session[:user_id]
      current_user
    else
      redirect_to '/', alert: I18n.t('access_denied')
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
# HomeController
# Shows the home page
class HomeController < ApplicationController
  def index
  end

  def log
  end
end

app/controllers/search_controller.rb
# SearchController
# Performs paginated API requests to GitHub's Search API
class SearchController < ApplicationController
  before_action :authenticate_user!
  before_action :init_search_form
  protect_from_forgery except: :index

  def index
  end

  private

  def init_search_form
    # @search_form = SearchFormDecorator.decorate(SearchForm.new(params.merge!(token: current_user.github_token)))
    @search_form = SearchForm.new(params.merge!(token: current_user.github_token))
  end
end

app/controllers/sessions_controller.rb
# SessionsController
# Provides authentication functions
class SessionsController < ApplicationController
  def create
    # binding.pry
    user = FindUserByOauth.call(auth_hash) || CreateUserFromOauth.call(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url # , notice: I18n.t('logged_in')
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: I18n.t('logged_out')
  end

  def failure
    redirect_to root_url, alert: I18n.t('authentication_failure')
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
# ApplicationHelper
# Use Draper where possible
module ApplicationHelper
  # nothing to see here
end

app/helpers/search_helper.rb
# SearchHelper
module SearchHelper
  def search_path_for(search_form, attrs = {})
    # binding.pry
    params = {
      language: attrs[:language] || search_form.language,
      order: attrs[:order] || search_form.order,
      page: attrs[:page] || search_form.page,
      q: attrs[:q] || search_form.q,
      sort: attrs[:sort] || search_form.sort
    }
    search_path(params)
  end
end

app/views/application/_flash.html.haml
.row
  .large-12.columns
    = display_flash_messages

app/views/application/_footer.html.haml
%footer.row
  .large-12.columns
    %hr
    .row
      .large-12.columns
        = image_tag 'githubby_couple.png'
    .row.bottom-bar
      .large-4.columns
        &copy;2015
        = link_to t('app_name'), 'http://githubbyapp.herokuapp.com/'
        by
        = link_to 'Stan Carver II', 'http://scarver2.github.io/'
      .large-4.columns.text-center
        = link_to 'Administration', admin_root_path
        |
        / = link_to 'Commit Logs', log_path
        / |
        = link_to 'Repo', 'https://github.com/scarver2/githubby_app'
      .large-4.columns
        .text-right.version
          = GitHubby::VERSION

app/views/application/_fork_me.html.haml
= link_to 'https://github.com/scarver2/githubby_app' do
  = image_tag 'https://camo.githubusercontent.com/567c3a48d796e2fc06ea80409cc9dd82bf714434/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f6461726b626c75655f3132313632312e706e67', alt: 'Fork me on GitHub', class: 'fork_me',  data: { 'canonical-src' => 'https://s3.amazonaws.com/github/ribbons/forkme_left_darkblue_121621.png' }

app/views/application/_header.html.haml
.row.top-bar
  .large-3.columns
    = link_to '/' do
      = image_tag 'githubby_logo_inverted.png'
  .large-6.columns
    = render 'search'
  .large-3.columns
    / %ul.button-group.right
    /   %li
    /     = render 'login'
    .right
      = render 'login'

app/views/application/_login.html.haml
- if current_user
  = %w(Aloha Bonjour Hello Hola Howdy Shalom).sample
  #{current_user.name}
  = link_to logout_path, title: t('logout') do
    %i.fi-power
- else
  = link_to '/auth/github', class: 'button' do
    %i.fi-social-github{title: 'GitHub'}
    = t('login')

app/views/application/_search.html.haml
- if current_user
  = render partial: 'search/form', locals: { search_form: @search_form || SearchForm.new }

app/views/home/index.html.haml
.row
  .large-12.columns
    = link_to 'https://bookshout.com/', target: :blank do
      = image_tag 'bs_slide_1.jpg'
    .text-right
      %small Advertisement

app/views/home/log.html.haml
- cache 'git_log', expires_in: 5.minutes do
  .row
    %pre
      = %x(git log --decorate)

app/views/layouts/application.html.haml
!!! 5
%html{ lang: 'en'}
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %title= content_for?(:title) ? yield(:title) : 'GitHubby'
    %meta{ description: 'If Octocat is a girl, this is where she would git her husband.' }
    %link{ href: '/opensearch.xml', rel: 'search', title: 'GitHubby', type: 'application/opensearchdescription+xml' }
    %link{ href: 'https://assets-cdn.github.com/favicon.ico', rel: 'icon', type: 'image/x-icon' }
    %link{ href: 'https://github.com/fluidicon.png', rel: 'fluid-icon', title: 'GitHub' }
    - %w(57 72 114 144).each do |size|
      %link{ href: "https://github.com/apple-touch-icon-#{size}.png", rel: 'apple-touch-icon', sizes: "#{size}x#{size}" }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    = render 'header'
    = render 'flash'
    = yield
    = render 'footer'

app/views/search/_form.html.haml
.row
  .large-12.columns
    = simple_form_for search_form, method: :get, url: search_path do |f|
      = f.input :q, label: false, input_html: { name: 'q' }

app/views/search/_pagination.html.haml
%ul.pagination
  %li.arrow{class: "#{'unavailable' if search_form.page == 1}"}
    = link_to search_path_for(search_form, page: search_form.previous_page), class: 'prev' do
      &laquo;
  - 1.upto(search_form.total_count / 30) do |n|
    %li{class: "#{'current' if search_form.page == n}"}
      = link_to n, search_path_for(search_form, page: n)
  %li.arrow{class: "#{'unavailable' unless search_form.next_page}"}
    = link_to search_path_for(search_form, page: search_form.next_page), class: 'next' do
      &raquo;

app/views/search/_table_header.html.haml
%thead
  %tr
    %th= I18n.t('name')
    %th
      %button.button.dropdown{aria: { controls: 'drop1', expanded: false }, data: { dropdown: 'drop1', href: '#' }}= I18n.t('language')
      %br
      %ul#drop1.f-dropdown{ aria: { hidden: true }, data: {'dropdown-content' => '' }}
        - if search_form.language
          %li= link_to '(none)', search_path_for(search_form, language: '', page: 1)
        - else
          - search_form.languages.each do |language|
            %li= link_to language, search_path_for(search_form, language: language, page: 1)
    %th
      - if search_form.order == 'desc'
        = link_to search_path_for(search_form, order: 'asc', page: 1, sort: 'stars') do
          = I18n.t('stargazers_count')
          %i.fi-arrow-down
      - else
        = link_to search_path_for(search_form, order: 'desc', page: 1, sort: 'stars') do
          = I18n.t('stargazers_count')
          %i.fi-arrow-up

app/views/search/index.html.haml
.row
  .large-12.columns
    %table#results
      = render partial: 'table_header', locals: { search_form: @search_form }
      %tbody
        = render @search_form.result
  
    = render partial: 'pagination', locals: { search_form: @search_form }

app/views/search/index.js.erb
$('#results tbody').append('<%= j render(@search_form.result) %>');
$('.pagination').replaceWith('<%= j render(partial: "pagination", locals: { search_form: @search_form }) %>');

app/views/search_results/_search_result.html.haml
%tr
  %td= search_result.name
  %td= search_result.language
  %td= search_result.stargazers_count